version: "3.5"
services:
    django:
        build: .
        container_name: imprint
        restart: always
        command: python umprint/manage.py runserver 127.0.0.1:8080/
        volumes:
            - .:/usr/src/app/
        ports:
            - 8080:8080
        environment:
            - DEBUG=True
            # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
