version: "3.7"
services:
    django:
        build: imprint-backend
        container_name: imprint
        restart: always
        command: python umprint/manage.py runserver 0.0.0.0:5000
        volumes:
            - .:/usr/src/app/
        ports:
            - "5000:5000"
        environment:
            - DEBUG=True
            # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - pgdb

    pgdb:
        image: postgres
        container_name: pgdb
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
