# Generated by Django 3.2.5 on 2021-07-08 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=20, unique=True, verbose_name='Почта')),
            ],
        ),
    ]
