# Generated by Django 3.2.5 on 2021-07-21 14:05

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Логин')),
                ('telegram_login', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Телеграм логин')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='Пароль')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=20, unique=True, verbose_name='Почта')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
